---

galaxy_info:
  author: zenoamaro
  description: A role to install and configure NGiNX
  version: 0.2
  license: MIT
  min_ansible_version: 1.4

  platforms:
    - name: Debian
    - name: Ubuntu
      versions:
        - precise
        - trusty

  categories:
    - web

dependencies: []
