---

# Boxed installation playbook
# ---------------------------

# A Simple, straight playbook for producing
# a boxed installation in a vagrant VM.


- name: 'Nginx boxed installation'

  hosts: vagrant

  # vars:
  #   custom_configuration: value

  post_tasks:
    # Produce a default site pointing to the shared folder
    - include: tasks/site.yml
      site: www
      port: 80
      server_name: 192.168.33.20
      access_log: /var/www/site/~access.log
      error_log: /var/www/site/~error.log
      document_root: /var/www/site

  roles:
    - '.'    # The current directory itself is the role

